# Site settings
title: Veladan Programming Blog
header-img: img/home-bg.jpg
email: daniel@veladan.org
description: "Veladan programming blog for all the programming issues I found."
baseurl: ""
url: "http://madcato.github.io"
twitter_username:  danieltvela
github_username:  madcato
linkedin_profile: https://www.linkedin.com/in/veladan/
stackoverflow_profile: https://stackoverflow.com/users/4815438/veladan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","bower_components"]
plugins: [jekyll-paginate]
sass:
    sass_dir: bower_components/bootstrap-sass/assets/stylesheets
# plugins:
#   - jekyll-polyglot
# 
# # language: https://github.com/untra/polyglot
# languages: ["en", "es"]
# default_lang: "en"
# exclude_from_localization: ["javascript", "images", "css"]
# parallel_localization: true