# Site settings
title_home: My blog
title: Veladan Programming Blog
header-img: img/home-bg.jpg
email: daniel@veladan.org
description: "...for all the programming issues I found."
baseurl: ""
url: "https://blog.veladan.org"
twitter_username:  danieltvela
github_username:  madcato
linkedin_username: veladan
stackoverflow_username: 4815438/veladan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["README.md"]
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
