# Site settings
title: Veladan Programming Blog
header-img: img/home-bg.jpg
email: daniel@veladan.org
description: "Veladan programming blog for all the programming issues I found."
baseurl: ""
url: "http://madcato.github.io"
github_username:  madcato

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","bower_components"]
plugins: [jekyll-paginate]
sass:
    sass_dir: bower_components/bootstrap-sass/assets/stylesheets
