# Site settings
title: Veladan Programming Blog
header-img: img/home-bg.jpg
email: daniel@veladan.org
description: "Veladan programming blog for all the programming issues I found."
baseurl: ""
url: "http://madcato.github.io"
twitter_username: veladan
github_username:  madcato
facebook_username:  veladan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
